apiVersion: v1
authProviders: []
blockNewUsers:
  enabled: false
  passlist: []
certificate:
  kind: secret
  name: https-certificates
containerRegistry:
  inCluster: true
  s3storage:
    bucket: gitpod
    certificate:
      kind: secret
      name: object-storage-gitpod-token
database:
  inCluster: false
  external:
    certificate:
      kind: secret
      name: mysql-gitpod-token
domain: vscode.steedos.cn
imagePullSecrets: null
jaegerOperator:
  inCluster: true
kind: Full
metadata:
  region: cn-northwest-1
objectStorage:
  inCluster: true
observability:
  logLevel: info
repository: 318804062415.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dockerhub/eu.gcr.io/gitpod-core-dev/build
workspace:
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
  runtime:
    containerdRuntimeDir: /var/lib/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/containerd/containerd.sock
    fsShiftMethod: shiftfs
